language: node_js
cache:
   directories:
       - ~!@.npm
node_js:
   - '9'
git:
   depth: 3
scripts:
   - yarn build
   - echo 'https://listtech.com.co' > public/CNAME
deploy:
   provider: pages
   skip-cleanup: true
   keep-history: true
   github-token: $GITHUB_TOKEN
   local-dir: build/
   target-branch: master
   commit_message: "Deploy Release ${TRAVIS_TAG}"
   on:
      branch: desarrollo