language: node_js
cache:
   directories:
       - ~/.npm
node_js:
   - '10.16.3'
git:
   depth: 25
   quiet: true
scripts:
   - yarn build
   - echo 'https://listtech.com.co' > public/CNAME
   - npm install
   - npm test
deploy:
   provider: pages
   skip-cleanup: true
   keep-history: true
   github-token: $GITHUB_TOKEN
   local-dir: build/
   target-branch: master
   commit_message: "Deploy Release ${TRAVIS_TAG}"
   on:
      branch: desarrollo
bundler_args: --retry 5      
